AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Trustworthy Model Registry

Resources:
  ModelRegistryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: model-registry
      Handler: src.api.lambda_handler  # <- will need a Lambda handler
      Runtime: python3.10
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
